import = [
    "~/.config/alacritty/themes/DjangoRebornAgain.toml"
]

[font]
size = 14
normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold = { family = "FiraCode Nerd Font", style = "Bold" }

[window]
padding = { x =5, y = 5 }